### ISSUE TITLE
Ambiguous occurrence ‘text’

### ISSUE THREAD

**Issue by dylantuttle** [jgm/gitit2#15]
I am trying to install gitit2, but I'm getting the following error message.

    Network/Gitit2.hs:545:39:
        Ambiguous occurrence ‘text’
        It could refer to either ‘Text.Pandoc.Builder.text’,
                                 imported from ‘Text.Pandoc.Builder’ at Network/Gitit2.hs:38:37-40
                              or ‘Text.Blaze.Html.text’,
                                 imported from ‘Text.Blaze.Html’ at Network/Gitit2.hs:51:1-40
                                 (and originally defined in ‘Text.Blaze.Internal’)
    Failed to install gitit2-0.0.0
    cabal: Error: some packages failed to install:
    gitit2-0.0.0 failed during the building phase. The exception was:
    ExitFailure 1

Any suggestions?

**Comment by jgm** [comment]
This means that your blaze-html and pandoc-types packages are compiled
against different versions of the text library.

You can either use a cabal sandbox or just remove your `~/.ghc`
directory (well, back it up somewhere) and `cabal install gitit2` again.
(This latter option will rebuild everything in a coherent way.)
I assume here that you are building cabal packages locally, which is
the default.

+++ Dylan Tuttle [Feb 10 15 17:09 ]:

**Comment by dylantuttle** [comment]
I tried `rm -rf ~/.ghc` and got the same error message. I also tried cabal sandbox with no luck.

```
$ cabal sandbox init
$ cabal install --only-dependencies
$ cabal build
```

I tried to modify Network/Gitit2.hs to import Text.Pandoc.Builder qualified. That just made things worse.

**Comment by jgm** [comment]
Sorry, I led you astray. Reading your report more carefully, I see that
this must be a case where a new version of blaze exported a symbol
'text' that it hadn't before.  Importing qualified should work, tough.
Let me look more closely.

+++ Dylan Tuttle [Feb 11 15 18:37 ]:

**Comment by jgm** [comment]
OK, I've pushed a change that ought to fix things (though I was never able to reproduce myself, so please test this).

**Comment by dylantuttle** [comment]
Yes, thank you. I'm now able to install, but I'm having trouble launching.

When I use `gitit2` to run, it gives me the following:

```
Creating initial repository in wikidata
12/Feb/2015:23:25:04 +0000 [Info#yesod-core] Application launched @(yesod-core-1.2.20.1:Yesod.Core.Dispatch ./Yesod/Core/Dispatch.hs:141:11)
```

When I try to connect through the browser, it resolves to http://localhost:3000/wiki instead of the public IP address. Here's the message I get on the server:

```
xx.xx.xx.xx - - [12/Feb/2015:23:30:17 +0000] "GET / HTTP/1.1" 303 - "" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36"
```

This may be a server issue in which case I apologize for the noise.

**Comment by jgm** [comment]
+++ Dylan Tuttle [Feb 12 15 15:57 ]:
>Yes, thank you. I'm now able to install, but I'm having trouble launching.
>
>When I use `gitit2` to run, it gives me the following:
>
>```
>Creating initial repository in wikidata
>12/Feb/2015:23:25:04 +0000 [Info#yesod-core] Application launched @(yesod-core-1.2.20.1:Yesod.Core.Dispatch ./Yesod/Core/Dispatch.hs:141:11)
>```
>
>When I try to connect through the browser, it resolves to http://localhost:3000/wiki instead of the public IP address. Here's the message I get on the server:
>
>```
>xx.xx.xx.xx - - [12/Feb/2015:23:30:17 +0000] "GET / HTTP/1.1" 303 - "" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36"
>```
>
>This may be a server issue in which case I apologize for the noise.

Probably so.  Are you using redirect instead of rewrite perhaps?

**Comment by dylantuttle** [comment]
I'm sorry. I neglected to change the approot settings :/
