### ISSUE TITLE
split up project into smaller files

### ISSUE THREAD

**Issue by thkoch2001** [jgm/gitit2#17]
I've just read fpcompletes tutorial ["Building a File Hosting Service in Yesod"](https://www.fpcomplete.com/school/advanced-haskell/building-a-file-hosting-service-in-yesod). They propose the same project structure as [described in the Yesod book](http://www.yesodweb.com/book/scaffolding-and-the-site-template) (see below).

For me it's already hard to read the gitit2 source code and I'd propose to split it up. Than it becomes clear, what things belong together, what parts depend on which other parts and one can quickly find stuff.

```
├── config
│   └── routes
├── Dispatch.hs   
├── Foundation.hs
├── Handler
│   ├── Home.hs
│   └── Preview.hs
├── Main.hs
└── templates
    ├── default-layout.cassius
    ├── default-layout.hamlet
    ├── default-layout-wrapper.hamlet
    ├── home.hamlet
    └── preview.hamlet
```

**Comment by jgm** [comment]
If you want to split things up this way and submit a PR, I'll certainly consider it!

+++ Thomas Koch [Apr 07 15 11:11 ]:

**Comment by thkoch2001** [comment]
It's also easier to navigate the projects Git history. Now almost every commit touches the same files.

**Comment by thkoch2001** [comment]
I'm still on my way, if you'd like to comment on a work-in-progress branch:
https://github.com/thkoch2001/gitit2/tree/wip_refactoring
